apiVersion: apps/v1
kind: Deployment
metadata:
  name: mario-game
spec:
  replicas: {{ .Values.mario.replicas }}
  selector:
    matchLabels:
      app: mario
  template:
    metadata:
      labels:
        app: mario
    spec:
      containers:
      - name: mario-container
        image: {{ .Values.mario.image }}       
        ports:
        - containerPort: 80
